version: '3'

services:
  testproject:
    build: .
    command: python3 testproject/manage.py test cc
    # command: python3 testproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - bitcoind

  bitcoind:
    image: btcpayserver/bitcoin:0.17.0
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |-
        rpcuser=ceiwHEbqWI83
        rpcpassword=DwubwWsoo3
        rpcport=43782
        port=39388
    ports:
      - "43782:43782"
    expose:
      - "43782"
